### ISSUE TITLE
Key already in storage

### ISSUE THREAD

**Issue by themarkymark-steem** [holgern/beem#125]
I am getting `key already in storage` when adding a key to the wallet on the Vit network.
When trying to use the key, it says 

`beem.exceptions.MissingKeyError`

I have tried removing the key, and adding again.  No luck.
`beempy --node https://jussi.vit.tube listaccounts `

Does not show the key.
Key was added (and removed) with `--node https://jussi.vit.tube` parameter.

It only happens to specific accounts, not all and on specific machines, where other keys work fine, but not some.

**Comment by holgern** [comment]
Thanks for reporting this, it should be fixed now.

**Comment by horsecoin** [comment]
It was working fine on osx importing the first two accouts, however now on the third and fourth account it won't let me add any more?  I think I just need to remove the keys and start fresh. How do I safely remove one account's keys so I can try to re-import?
Wallet Unlocked!
Account Passphrase: 
Importing active key!
Traceback (most recent call last):
  File "/usr/local/bin/beempy", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/beem/cli.py", line 1413, in importaccount
    stm.wallet.addPrivateKey(active_privkey)
  File "/usr/local/lib/python3.7/site-packages/beem/wallet.py", line 428, in addPrivateKey
    self.keyStorage.add(self.encrypt_wif(wif), pub)
  File "/usr/local/lib/python3.7/site-packages/beem/storage.py", line 238, in add
    raise ValueError("Key already in storage")
ValueError: Key already in storage
