### ISSUE TITLE
KeyError: 'sbd_payout'

### ISSUE THREAD

**Issue by photobook-hive** [holgern/beem#263]
Got this error with the new 0.24.11 while try to get rewards.

user@server:~/hivegame $ /home/pi/.local/bin/beempy rewards -t -p -d 3 playcard
Traceback (most recent call last):
  File "/home/pi/.local/bin/beempy", line 10, in <module>
    sys.exit(cli())
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/click_shell/core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/beem/cli.py", line 4192, in rewards
    payout_SBD = Amount(v["sbd_payout"], blockchain_instance=stm)
KeyError: 'sbd_payout'

**Comment by holgern** [comment]
Will be fixed in 0.24.12

**Comment by photobook-hive** [comment]
Top! Thanks
