### ISSUE TITLE
BEEMPY rewards > list index ot of range

### ISSUE THREAD

**Issue by photobook-hive** [holgern/beem#269]
pi@wassermann:~ $ /home/pi/.local/bin/beempy rewards playcard
Traceback (most recent call last):
  File "/home/pi/.local/bin/beempy", line 11, in <module>
    load_entry_point('beem==0.24.14', 'console_scripts', 'beempy')()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click_shell/core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/beem-0.24.14-py3.7.egg/beem/cli.py", line 4199, in rewards
  File "/home/pi/.local/lib/python3.7/site-packages/beem-0.24.14-py3.7.egg/beem/account.py", line 1919, in estimate_virtual_op_num
  File "/home/pi/.local/lib/python3.7/site-packages/beem-0.24.14-py3.7.egg/beem/account.py", line 1912, in get_blocknum
IndexError: list index out of range

**Comment by holgern** [comment]
Please update to 0.24.19, the bug has already been solved.
