### ISSUE TITLE
'PointJacobi' object has no attribute '_Point__x'

### ISSUE THREAD

**Issue by photobook-hive** [holgern/beem#275]
/usr/local/bin/beempy --keys XXX powerup -a XXX0.180

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/beemgraphenebase/ecdsasig.py", line 102, in recover_public_key
    public_key = ec.EllipticCurvePublicNumbers(Q_point.x(), Q_point.y(), ec.SECP256K1()).public_key(default_backend())
  File "/home/pi/.local/lib/python3.7/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 345, in __init__
    raise TypeError("x and y must be integers.")
TypeError: x and y must be integers.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/beempy", line 10, in <module>
    sys.exit(cli())
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/click_shell/core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/beem/cli.py", line 1332, in powerup
    tx = acc.transfer_to_vesting(amount, to=to)
  File "/usr/local/lib/python3.7/dist-packages/beem/account.py", line 2976, in transfer_to_vesting
    return self.blockchain.finalizeOp(op, account, "active", **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/beem/blockchaininstance.py", line 936, in finalizeOp
    ret_sign = self.txbuffer.sign()
  File "/usr/local/lib/python3.7/dist-packages/beem/transactionbuilder.py", line 443, in sign
    self.tx.sign(self.wifs, chain=self.blockchain.chain_params)
  File "/usr/local/lib/python3.7/dist-packages/beembase/signedtransactions.py", line 35, in sign
    return super(Signed_Transaction, self).sign(wifkeys, chain)
  File "/usr/local/lib/python3.7/dist-packages/beemgraphenebase/signedtransactions.py", line 195, in sign
    signature = sign_message(self.message, wif)
  File "/usr/local/lib/python3.7/dist-packages/beemgraphenebase/ecdsasig.py", line 201, in sign_message
    message, digest, signature, public_key)
  File "/usr/local/lib/python3.7/dist-packages/beemgraphenebase/ecdsasig.py", line 127, in recoverPubkeyParameter
    p = recover_public_key(digest, signature, i, message)
  File "/usr/local/lib/python3.7/dist-packages/beemgraphenebase/ecdsasig.py", line 104, in recover_public_key
    public_key = ec.EllipticCurvePublicNumbers(Q._Point__x, Q._Point__y, ec.SECP256K1()).public_key(default_backend())
AttributeError: 'PointJacobi' object has no attribute '_Point__x'

**Comment by holgern** [comment]
This will be fixed in the next release
