### ISSUE TITLE
Account.history() fails with float division by zero exception

### ISSUE THREAD

**Issue by crokkon** [holgern/beem#34]
#### Expected behavior
`Account.history(start, stop)` with `start` and `stop` being datetime instances should return all account operations between the given timestamps

#### Actual behavior
`Account.history(start, stop)` sometimes fails with a `ZeroDivisionError` exception:

```
Traceback (most recent call last):
  File "history.py", line 15, in <module>
    for op in a.history(start, stop):
  File "/usr/local/lib/python3.6/site-packages/beem/account.py", line 1566, in history
    op_est = self.estimate_virtual_op_num(start, stop_diff=1)
  File "/usr/local/lib/python3.6/site-packages/beem/account.py", line 1333, in estimate_virtual_op_num
    op_diff = (blocktime - formatTimeString(trx["timestamp"])).total_seconds() / factor
ZeroDivisionError: float division by zero
```

#### How to reproduce

What actually fails is the op number lookup for a given timestamp via `Account.estimate_virtual_op_num()`. Here's a minimum example to reproduce the problem:

```
from beem.account import Account
from datetime import datetime, timedelta
from beem.utils import addTzInfo
a = Account("berniesanders")
start = addTzInfo(datetime(2017, 11, 16, 23, 23, 11))
print(a.estimate_virtual_op_num(start))
```

Output:

```
# python bug_divbyzero.py 
Traceback (most recent call last):
  File "bug_divbyzero.py", line 9, in <module>
    print(a.estimate_virtual_op_num(start))
  File "/usr/local/lib/python3.6/site-packages/beem/account.py", line 1333, in estimate_virtual_op_num
    op_diff = (blocktime - formatTimeString(trx["timestamp"])).total_seconds() / factor
ZeroDivisionError: float division by zero
```

The following quick-hack solves the problem in this case:
```diff
diff --git a/beem/account.py b/beem/account.py
index e100a58..c840185 100644
--- a/beem/account.py
+++ b/beem/account.py
@@ -1329,6 +1329,7 @@ class Account(BlockchainObject):
                     factor = (formatTimeString(op_start_last[0][1]["timestamp"]) - formatTimeString(trx["timestamp"])).total_seconds() / diff_op
                 elif not isinstance(blocktime, (datetime, date, time)) and diff_op != 0:
                     factor = (op_start_last[0][1]["block"] - trx["block"]) / diff_op
+                factor = min(1, factor)
             if isinstance(blocktime, (datetime, date, time)):
                 op_diff = (blocktime - formatTimeString(trx["timestamp"])).total_seconds() / factor
             else:
```
However, there are more instances where a division by `factor` is done and I'm not sure if the change affects the correctness of the resulting block number.

#### Environment
```
# beempy --version
beempy, version 0.19.40
# python --version
Python 3.6.5
```

**Comment by crokkon** [comment]
Correction: don't implement my quick-hack, `op_diff` can be negative and so can `factor` - `min(1, factor)` would break this. 
I think the issue is caused by the fact that an account can have several ops in the same block. `op_start_last[0][1]["timestamp"])` and `trx["timestamp"]` can be identical in this case. This makes `factor = 0`.

I think there's another potential issue here:

https://github.com/holgern/beem/blob/764865398f6a14c31a7c0323ce2f864b0de9ab50/beem/account.py#L1328

if `diff_op == 0`, the `factor` assignment is skipped and `factor` is used later on with the value from the previous iteration or from the initial assignment outside the `while` loop.
