### ISSUE TITLE
Problem with validating signatures interaction with ECDSA library

### ISSUE THREAD

**Issue by brianoflondon** [holgern/beem#455]
Getting this error trying to authenticate in Python the response from a Hive Keychain signature
```
2024-02-01 11:07:57,758 ERROR    auth             120 : Traceback (most recent call last):
  File "/app/v4vapp_api_ext/routers/auth.py", line 93, in validate_hivekeychain_ans
    msgkey = verify_message(enc_msg, unhexlify(signature))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/beemgraphenebase/ecdsasig.py", line 283, in verify_message
    pub = secp256k1.PublicKey(flags=ALL_FLAGS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Assignees: @brianoflondon
Labels:
Milestone:

**Comment by steevc** [comment]
Is anyone maintaining beem? It may mostly work, but will fall behind.
